from RnaToProteinDataModule.NasModel import NasModel
from RnaToProteinDataModule.RnaToProteinModule import RnaToProteinDataModule
from RnaToProteinDataModule.Premade_models.models import run, make_nas14